prefix: pw
azure_region: eastus
vnet_address_space: "10.1.0.0/16"
public_subnet_cidrs:
  - "10.1.1.0/24"
  - "10.1.2.0/24"
private_subnet_cidrs:
  - "10.1.3.0/24"
  - "10.1.4.0/24"
nat_gateway_name: pw-natgw
nat_gateway_sku: Standard
resource_group_name: personal-workspace-backend-rg